[package]
name = "wicked-waifus-asset-updater"
edition = "2021"
version.workspace = true

[dependencies]
git2 = "0.20.0"
ureq = "3.0.5"
zip-extract = "0.2.1"

tracing.workspace = true
thiserror.workspace = true
