[network]
http_addr = "0.0.0.0:10001"

[encryption]
key = "t+AEu5SGdpz06tomonajLMau9AJgmyTvVhz9VtGf1+0="
iv = "fprc5lBWADQB7tim0R2JxQ=="

[serve]
serve_web_path = "/"
serve_dir_path = "data/assets/config-server"

[asset_config]
repository_url = "https://git.xeondev.com/wickedwaifus/wicked-waifus-config-server-files.git"
reference = "a7ad3d4ef8"
discard_local_changes = true