[package]
name = "wicked-waifus-commons"
edition = "2021"
version.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

toml.workspace = true
serde.workspace = true
